#include <iostream>
using namespace std;
int main(){
char ADD_DEBIT;
float LAND_AND_BUILDING;
float OFFICE_EQUIPMENT;
float INVENTORY;
float CASH;
cout<< "ENTER THE DEBIT SIDE OF THE BALANCE SHEET\n";
cout<< "ENTER THE ASSETS\n";
cout<< "ENTER + SYMBOL TO ADD THE ASSETS: ";
cin>> ADD_DEBIT;
cout<< "ENTER OPERATOR LAND AND BUILDING: ";
cin>> LAND_AND_BUILDING;
cout<< "ENTER OPERATOR OFFICE EQUIPMENT: ";
cin>> OFFICE_EQUIPMENT;
cout<< "ENTER OPERATOR INVENTORY: ";
cin>> INVENTORY;
switch(ADD_DEBIT){
case '+':
    cout<< "YOUR DEBIT IS"<< " "<<LAND_AND_BUILDING+OFFICE_EQUIPMENT+INVENTORY+CASH<< "\n";
    break;
}
char ADD_CREDIT;
float BANK_LOANS_AMOUNT;
float ACCOUNTS_PAYABLE_AMOUNT;
float EQUITY_PAID_IN_CAPITAL;
float RETAINED_EARNINGS;
cout<< "ENTER THE CREDIT SIDE\n";
cout<< "ENTER LIABILITIES\n";
cout<< "ENTER + SYMBOL TO ADD THE LIABILITIES: ";
cin>> ADD_CREDIT;
cout<< "ENTER BANK LOANS AMOUNT: ";
cin>> BANK_LOANS_AMOUNT;
cout<< "ENTER ACCOUNTS PAYABLE TOTAL AMOUNT: ";
cin>> ACCOUNTS_PAYABLE_AMOUNT;
cout<< "ENTER EQUITY TOTAL AMOUNTS\n";
cout<< "ENTER EQUITY PAID IN CAPITAL: ";
cin>> EQUITY_PAID_IN_CAPITAL;
cout<< "ENTER RETAINED EARNINGS: ";
cin>> RETAINED_EARNINGS;
switch(ADD_CREDIT){
case '+':
    cout<< "YOUR TOTAL LIABILITIES IS"<< " "<<BANK_LOANS_AMOUNT+ACCOUNTS_PAYABLE_AMOUNT<< "\n";
    cout<< "YOUR TOTAL EQUITY IS"<< " "<<EQUITY_PAID_IN_CAPITAL+RETAINED_EARNINGS<< "\n";
    break;
}
cout<< ADD_DEBIT;
cout<< ADD_CREDIT;
if (ADD_DEBIT>=ADD_CREDIT){
    cout << "YOUR  "<< " "<<BANK_LOANS_AMOUNT+ACCOUNTS_PAYABLE_AMOUNT<< "\n";
}
return 0;
}
